FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY ./services/analyzer/go.mod ./services/analyzer/go.sum ./
RUN go mod download

COPY ./services/analyzer/ ./
RUN go build -o main ./main.go

EXPOSE 9094

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
CMD ["./main"]
