# Use a lightweight Go image as the base
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./ ./
RUN go build -o main ./services/gateway/main.go

EXPOSE 8080

FROM scratch
COPY --from=builder /app/main .
CMD ["./main"]