# Use a lightweight Go image as the base
FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./ ./
RUN go build -o main ./services/agent/main.go

EXPOSE 8080

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/main .
CMD ["./main"]