# Use a lightweight Go image as the base
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY ./services/agent/go.mod ./services/agent/go.sum ./
RUN go mod download

COPY ./services/agent/ ./
RUN go build -o main ./main.go

EXPOSE 8080

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/main .
CMD ["./main"]