// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: implementation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImplementationService_ImplementPlan_FullMethodName           = "/implementation.ImplementationService/ImplementPlan"
	ImplementationService_GetImplementationStatus_FullMethodName = "/implementation.ImplementationService/GetImplementationStatus"
	ImplementationService_GetImplementationResult_FullMethodName = "/implementation.ImplementationService/GetImplementationResult"
)

// ImplementationServiceClient is the client API for ImplementationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Implementation Service - 코드 구현 (비동기)
type ImplementationServiceClient interface {
	// 코드 구현 시작 (비동기, Job ID 반환)
	ImplementPlan(ctx context.Context, in *ImplementPlanRequest, opts ...grpc.CallOption) (*ImplementPlanResponse, error)
	// 구현 상태 조회
	GetImplementationStatus(ctx context.Context, in *GetImplementationStatusRequest, opts ...grpc.CallOption) (*GetImplementationStatusResponse, error)
	// 구현 결과 조회
	GetImplementationResult(ctx context.Context, in *GetImplementationResultRequest, opts ...grpc.CallOption) (*GetImplementationResultResponse, error)
}

type implementationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImplementationServiceClient(cc grpc.ClientConnInterface) ImplementationServiceClient {
	return &implementationServiceClient{cc}
}

func (c *implementationServiceClient) ImplementPlan(ctx context.Context, in *ImplementPlanRequest, opts ...grpc.CallOption) (*ImplementPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImplementPlanResponse)
	err := c.cc.Invoke(ctx, ImplementationService_ImplementPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *implementationServiceClient) GetImplementationStatus(ctx context.Context, in *GetImplementationStatusRequest, opts ...grpc.CallOption) (*GetImplementationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImplementationStatusResponse)
	err := c.cc.Invoke(ctx, ImplementationService_GetImplementationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *implementationServiceClient) GetImplementationResult(ctx context.Context, in *GetImplementationResultRequest, opts ...grpc.CallOption) (*GetImplementationResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImplementationResultResponse)
	err := c.cc.Invoke(ctx, ImplementationService_GetImplementationResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImplementationServiceServer is the server API for ImplementationService service.
// All implementations must embed UnimplementedImplementationServiceServer
// for forward compatibility.
//
// Implementation Service - 코드 구현 (비동기)
type ImplementationServiceServer interface {
	// 코드 구현 시작 (비동기, Job ID 반환)
	ImplementPlan(context.Context, *ImplementPlanRequest) (*ImplementPlanResponse, error)
	// 구현 상태 조회
	GetImplementationStatus(context.Context, *GetImplementationStatusRequest) (*GetImplementationStatusResponse, error)
	// 구현 결과 조회
	GetImplementationResult(context.Context, *GetImplementationResultRequest) (*GetImplementationResultResponse, error)
	mustEmbedUnimplementedImplementationServiceServer()
}

// UnimplementedImplementationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImplementationServiceServer struct{}

func (UnimplementedImplementationServiceServer) ImplementPlan(context.Context, *ImplementPlanRequest) (*ImplementPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImplementPlan not implemented")
}
func (UnimplementedImplementationServiceServer) GetImplementationStatus(context.Context, *GetImplementationStatusRequest) (*GetImplementationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImplementationStatus not implemented")
}
func (UnimplementedImplementationServiceServer) GetImplementationResult(context.Context, *GetImplementationResultRequest) (*GetImplementationResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImplementationResult not implemented")
}
func (UnimplementedImplementationServiceServer) mustEmbedUnimplementedImplementationServiceServer() {}
func (UnimplementedImplementationServiceServer) testEmbeddedByValue()                               {}

// UnsafeImplementationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImplementationServiceServer will
// result in compilation errors.
type UnsafeImplementationServiceServer interface {
	mustEmbedUnimplementedImplementationServiceServer()
}

func RegisterImplementationServiceServer(s grpc.ServiceRegistrar, srv ImplementationServiceServer) {
	// If the following call pancis, it indicates UnimplementedImplementationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImplementationService_ServiceDesc, srv)
}

func _ImplementationService_ImplementPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImplementPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplementationServiceServer).ImplementPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImplementationService_ImplementPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplementationServiceServer).ImplementPlan(ctx, req.(*ImplementPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImplementationService_GetImplementationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImplementationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplementationServiceServer).GetImplementationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImplementationService_GetImplementationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplementationServiceServer).GetImplementationStatus(ctx, req.(*GetImplementationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImplementationService_GetImplementationResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImplementationResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplementationServiceServer).GetImplementationResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImplementationService_GetImplementationResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplementationServiceServer).GetImplementationResult(ctx, req.(*GetImplementationResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImplementationService_ServiceDesc is the grpc.ServiceDesc for ImplementationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImplementationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "implementation.ImplementationService",
	HandlerType: (*ImplementationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImplementPlan",
			Handler:    _ImplementationService_ImplementPlan_Handler,
		},
		{
			MethodName: "GetImplementationStatus",
			Handler:    _ImplementationService_GetImplementationStatus_Handler,
		},
		{
			MethodName: "GetImplementationResult",
			Handler:    _ImplementationService_GetImplementationResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "implementation.proto",
}
