// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: implementation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImplementPlan 요청/응답
type ImplementPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 구현할 개발 계획 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanRequest) Reset() {
	*x = ImplementPlanRequest{}
	mi := &file_implementation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanRequest) ProtoMessage() {}

func (x *ImplementPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanRequest.ProtoReflect.Descriptor instead.
func (*ImplementPlanRequest) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{0}
}

func (x *ImplementPlanRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

type ImplementPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`     // Job ID (상태 조회용)
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`   // 초기 상태 (pending)
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 메시지
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanResponse) Reset() {
	*x = ImplementPlanResponse{}
	mi := &file_implementation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanResponse) ProtoMessage() {}

func (x *ImplementPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanResponse.ProtoReflect.Descriptor instead.
func (*ImplementPlanResponse) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{1}
}

func (x *ImplementPlanResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ImplementPlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImplementPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetImplementationStatus 요청/응답
type GetImplementationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"` // Job ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImplementationStatusRequest) Reset() {
	*x = GetImplementationStatusRequest{}
	mi := &file_implementation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImplementationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationStatusRequest) ProtoMessage() {}

func (x *GetImplementationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetImplementationStatusRequest) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{2}
}

func (x *GetImplementationStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetImplementationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`             // Job ID
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`           // 상태 (pending, processing, completed, failed)
	Progress      int32                  `protobuf:"varint,3,opt,name=Progress,proto3" json:"Progress,omitempty"`      // 진행률 (0-100)
	CurrentStep   string                 `protobuf:"bytes,4,opt,name=CurrentStep,proto3" json:"CurrentStep,omitempty"` // 현재 단계 설명
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`     // 생성 시간
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`     // 업데이트 시간
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImplementationStatusResponse) Reset() {
	*x = GetImplementationStatusResponse{}
	mi := &file_implementation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImplementationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationStatusResponse) ProtoMessage() {}

func (x *GetImplementationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetImplementationStatusResponse) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{3}
}

func (x *GetImplementationStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetImplementationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetImplementationStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetImplementationStatusResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *GetImplementationStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetImplementationStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetImplementationResult 요청/응답
type GetImplementationResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"` // Job ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImplementationResultRequest) Reset() {
	*x = GetImplementationResultRequest{}
	mi := &file_implementation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImplementationResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationResultRequest) ProtoMessage() {}

func (x *GetImplementationResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationResultRequest.ProtoReflect.Descriptor instead.
func (*GetImplementationResultRequest) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{4}
}

func (x *GetImplementationResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Diagram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagram       string                 `protobuf:"bytes,1,opt,name=Diagram,proto3" json:"Diagram,omitempty"` // Mermaid 다이어그램 코드
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`       // 다이어그램 타입 (classDiagram, sequenceDiagram, flowchart)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagram) Reset() {
	*x = Diagram{}
	mi := &file_implementation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagram) ProtoMessage() {}

func (x *Diagram) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagram.ProtoReflect.Descriptor instead.
func (*Diagram) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{5}
}

func (x *Diagram) GetDiagram() string {
	if x != nil {
		return x.Diagram
	}
	return ""
}

func (x *Diagram) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExplainedSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLine     int32                  `protobuf:"varint,1,opt,name=StartLine,proto3" json:"StartLine,omitempty"`    // 시작 라인 (0-indexed)
	EndLine       int32                  `protobuf:"varint,2,opt,name=EndLine,proto3" json:"EndLine,omitempty"`        // 종료 라인
	Explanation   string                 `protobuf:"bytes,3,opt,name=Explanation,proto3" json:"Explanation,omitempty"` // 한국어 설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainedSegment) Reset() {
	*x = ExplainedSegment{}
	mi := &file_implementation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainedSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainedSegment) ProtoMessage() {}

func (x *ExplainedSegment) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainedSegment.ProtoReflect.Descriptor instead.
func (*ExplainedSegment) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{6}
}

func (x *ExplainedSegment) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *ExplainedSegment) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *ExplainedSegment) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type GetImplementationResultResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`                         // Job ID
	Status            string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`                       // 상태
	Code              string                 `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`                           // 생성된 코드
	Diagrams          []*Diagram             `protobuf:"bytes,4,rep,name=Diagrams,proto3" json:"Diagrams,omitempty"`                   // 다이어그램 목록
	ExplainedSegments []*ExplainedSegment    `protobuf:"bytes,5,rep,name=ExplainedSegments,proto3" json:"ExplainedSegments,omitempty"` // 코드 설명 구간
	Error             string                 `protobuf:"bytes,6,opt,name=Error,proto3" json:"Error,omitempty"`                         // 에러 메시지 (실패 시)
	CompletedAt       string                 `protobuf:"bytes,7,opt,name=CompletedAt,proto3" json:"CompletedAt,omitempty"`             // 완료 시간
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetImplementationResultResponse) Reset() {
	*x = GetImplementationResultResponse{}
	mi := &file_implementation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImplementationResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationResultResponse) ProtoMessage() {}

func (x *GetImplementationResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_implementation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationResultResponse.ProtoReflect.Descriptor instead.
func (*GetImplementationResultResponse) Descriptor() ([]byte, []int) {
	return file_implementation_proto_rawDescGZIP(), []int{7}
}

func (x *GetImplementationResultResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetImplementationResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetImplementationResultResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetImplementationResultResponse) GetDiagrams() []*Diagram {
	if x != nil {
		return x.Diagrams
	}
	return nil
}

func (x *GetImplementationResultResponse) GetExplainedSegments() []*ExplainedSegment {
	if x != nil {
		return x.ExplainedSegments
	}
	return nil
}

func (x *GetImplementationResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetImplementationResultResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

var File_implementation_proto protoreflect.FileDescriptor

const file_implementation_proto_rawDesc = "" +
	"\n" +
	"\x14implementation.proto\x12\x0eimplementation\"4\n" +
	"\x14ImplementPlanRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\"_\n" +
	"\x15ImplementPlanResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"6\n" +
	"\x1eGetImplementationStatusRequest\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\"\xc9\x01\n" +
	"\x1fGetImplementationStatusResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x1a\n" +
	"\bProgress\x18\x03 \x01(\x05R\bProgress\x12 \n" +
	"\vCurrentStep\x18\x04 \x01(\tR\vCurrentStep\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x06 \x01(\tR\tUpdatedAt\"6\n" +
	"\x1eGetImplementationResultRequest\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\"7\n" +
	"\aDiagram\x12\x18\n" +
	"\aDiagram\x18\x01 \x01(\tR\aDiagram\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\"l\n" +
	"\x10ExplainedSegment\x12\x1c\n" +
	"\tStartLine\x18\x01 \x01(\x05R\tStartLine\x12\x18\n" +
	"\aEndLine\x18\x02 \x01(\x05R\aEndLine\x12 \n" +
	"\vExplanation\x18\x03 \x01(\tR\vExplanation\"\xa0\x02\n" +
	"\x1fGetImplementationResultResponse\x12\x14\n" +
	"\x05JobId\x18\x01 \x01(\tR\x05JobId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\tR\x04Code\x123\n" +
	"\bDiagrams\x18\x04 \x03(\v2\x17.implementation.DiagramR\bDiagrams\x12N\n" +
	"\x11ExplainedSegments\x18\x05 \x03(\v2 .implementation.ExplainedSegmentR\x11ExplainedSegments\x12\x14\n" +
	"\x05Error\x18\x06 \x01(\tR\x05Error\x12 \n" +
	"\vCompletedAt\x18\a \x01(\tR\vCompletedAt2\xed\x02\n" +
	"\x15ImplementationService\x12\\\n" +
	"\rImplementPlan\x12$.implementation.ImplementPlanRequest\x1a%.implementation.ImplementPlanResponse\x12z\n" +
	"\x17GetImplementationStatus\x12..implementation.GetImplementationStatusRequest\x1a/.implementation.GetImplementationStatusResponse\x12z\n" +
	"\x17GetImplementationResult\x12..implementation.GetImplementationResultRequest\x1a/.implementation.GetImplementationResultResponseB$Z\"codev42/services/implementation/pbb\x06proto3"

var (
	file_implementation_proto_rawDescOnce sync.Once
	file_implementation_proto_rawDescData []byte
)

func file_implementation_proto_rawDescGZIP() []byte {
	file_implementation_proto_rawDescOnce.Do(func() {
		file_implementation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_implementation_proto_rawDesc), len(file_implementation_proto_rawDesc)))
	})
	return file_implementation_proto_rawDescData
}

var file_implementation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_implementation_proto_goTypes = []any{
	(*ImplementPlanRequest)(nil),            // 0: implementation.ImplementPlanRequest
	(*ImplementPlanResponse)(nil),           // 1: implementation.ImplementPlanResponse
	(*GetImplementationStatusRequest)(nil),  // 2: implementation.GetImplementationStatusRequest
	(*GetImplementationStatusResponse)(nil), // 3: implementation.GetImplementationStatusResponse
	(*GetImplementationResultRequest)(nil),  // 4: implementation.GetImplementationResultRequest
	(*Diagram)(nil),                         // 5: implementation.Diagram
	(*ExplainedSegment)(nil),                // 6: implementation.ExplainedSegment
	(*GetImplementationResultResponse)(nil), // 7: implementation.GetImplementationResultResponse
}
var file_implementation_proto_depIdxs = []int32{
	5, // 0: implementation.GetImplementationResultResponse.Diagrams:type_name -> implementation.Diagram
	6, // 1: implementation.GetImplementationResultResponse.ExplainedSegments:type_name -> implementation.ExplainedSegment
	0, // 2: implementation.ImplementationService.ImplementPlan:input_type -> implementation.ImplementPlanRequest
	2, // 3: implementation.ImplementationService.GetImplementationStatus:input_type -> implementation.GetImplementationStatusRequest
	4, // 4: implementation.ImplementationService.GetImplementationResult:input_type -> implementation.GetImplementationResultRequest
	1, // 5: implementation.ImplementationService.ImplementPlan:output_type -> implementation.ImplementPlanResponse
	3, // 6: implementation.ImplementationService.GetImplementationStatus:output_type -> implementation.GetImplementationStatusResponse
	7, // 7: implementation.ImplementationService.GetImplementationResult:output_type -> implementation.GetImplementationResultResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_implementation_proto_init() }
func file_implementation_proto_init() {
	if File_implementation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_implementation_proto_rawDesc), len(file_implementation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_implementation_proto_goTypes,
		DependencyIndexes: file_implementation_proto_depIdxs,
		MessageInfos:      file_implementation_proto_msgTypes,
	}.Build()
	File_implementation_proto = out.File
	file_implementation_proto_goTypes = nil
	file_implementation_proto_depIdxs = nil
}
