// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=Prompt,proto3" json:"Prompt,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanRequest) Reset() {
	*x = GeneratePlanRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanRequest) ProtoMessage() {}

func (x *GeneratePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanRequest.ProtoReflect.Descriptor instead.
func (*GeneratePlanRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePlanRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GeneratePlanRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GeneratePlanRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type Annotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Params        string                 `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`
	Returns       string                 `protobuf:"bytes,3,opt,name=Returns,proto3" json:"Returns,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Annotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Annotation) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Annotation) GetReturns() string {
	if x != nil {
		return x.Returns
	}
	return ""
}

func (x *Annotation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=ClassName,proto3" json:"ClassName,omitempty"`
	Annotations   []*Annotation          `protobuf:"bytes,2,rep,name=Annotations,proto3" json:"Annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Plan) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Plan) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GeneratePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`
	Plans         []*Plan                `protobuf:"bytes,3,rep,name=Plans,proto3" json:"Plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanResponse) Reset() {
	*x = GeneratePlanResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanResponse) ProtoMessage() {}

func (x *GeneratePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanResponse.ProtoReflect.Descriptor instead.
func (*GeneratePlanResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratePlanResponse) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *GeneratePlanResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeneratePlanResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type SaveCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCodeRequest) Reset() {
	*x = SaveCodeRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCodeRequest) ProtoMessage() {}

func (x *SaveCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCodeRequest.ProtoReflect.Descriptor instead.
func (*SaveCodeRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SaveCodeRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SaveCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SaveCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCodeResponse) Reset() {
	*x = SaveCodeResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCodeResponse) ProtoMessage() {}

func (x *SaveCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCodeResponse.ProtoReflect.Descriptor instead.
func (*SaveCodeResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SaveCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ImplementPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanRequest) Reset() {
	*x = ImplementPlanRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanRequest) ProtoMessage() {}

func (x *ImplementPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanRequest.ProtoReflect.Descriptor instead.
func (*ImplementPlanRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ImplementPlanRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

type ImplementPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=Codes,proto3" json:"Codes,omitempty"`
	Diagram       string                 `protobuf:"bytes,2,opt,name=Diagram,proto3" json:"Diagram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanResponse) Reset() {
	*x = ImplementPlanResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanResponse) ProtoMessage() {}

func (x *ImplementPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanResponse.ProtoReflect.Descriptor instead.
func (*ImplementPlanResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ImplementPlanResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *ImplementPlanResponse) GetDiagram() string {
	if x != nil {
		return x.Diagram
	}
	return ""
}

type ModifyPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`
	Plans         []*Plan                `protobuf:"bytes,3,rep,name=Plans,proto3" json:"Plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPlanRequest) Reset() {
	*x = ModifyPlanRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPlanRequest) ProtoMessage() {}

func (x *ModifyPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPlanRequest.ProtoReflect.Descriptor instead.
func (*ModifyPlanRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyPlanRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *ModifyPlanRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ModifyPlanRequest) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type ModifyPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPlanResponse) Reset() {
	*x = ModifyPlanResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPlanResponse) ProtoMessage() {}

func (x *ModifyPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPlanResponse.ProtoReflect.Descriptor instead.
func (*ModifyPlanResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyPlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPlanByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByIdRequest) Reset() {
	*x = GetPlanByIdRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByIdRequest) ProtoMessage() {}

func (x *GetPlanByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlanByIdRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlanByIdRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

type GetPlanByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=Language,proto3" json:"Language,omitempty"`
	Plans         []*Plan                `protobuf:"bytes,5,rep,name=Plans,proto3" json:"Plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByIdResponse) Reset() {
	*x = GetPlanByIdResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByIdResponse) ProtoMessage() {}

func (x *GetPlanByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPlanByIdResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlanByIdResponse) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *GetPlanByIdResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetPlanByIdResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetPlanByIdResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetPlanByIdResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x02pb\"c\n" +
	"\x13GeneratePlanRequest\x12\x16\n" +
	"\x06Prompt\x18\x01 \x01(\tR\x06Prompt\x12\x1c\n" +
	"\tProjectId\x18\x02 \x01(\tR\tProjectId\x12\x16\n" +
	"\x06Branch\x18\x03 \x01(\tR\x06Branch\"t\n" +
	"\n" +
	"Annotation\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x01(\tR\x06Params\x12\x18\n" +
	"\aReturns\x18\x03 \x01(\tR\aReturns\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\"V\n" +
	"\x04Plan\x12\x1c\n" +
	"\tClassName\x18\x01 \x01(\tR\tClassName\x120\n" +
	"\vAnnotations\x18\x02 \x03(\v2\x0e.pb.AnnotationR\vAnnotations\"p\n" +
	"\x14GeneratePlanResponse\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1a\n" +
	"\bLanguage\x18\x02 \x01(\tR\bLanguage\x12\x1e\n" +
	"\x05Plans\x18\x03 \x03(\v2\b.pb.PlanR\x05Plans\"A\n" +
	"\x0fSaveCodeRequest\x12\x1a\n" +
	"\bFilePath\x18\x01 \x01(\tR\bFilePath\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\"*\n" +
	"\x10SaveCodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"4\n" +
	"\x14ImplementPlanRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\"G\n" +
	"\x15ImplementPlanResponse\x12\x14\n" +
	"\x05Codes\x18\x01 \x03(\tR\x05Codes\x12\x18\n" +
	"\aDiagram\x18\x02 \x01(\tR\aDiagram\"m\n" +
	"\x11ModifyPlanRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1a\n" +
	"\bLanguage\x18\x02 \x01(\tR\bLanguage\x12\x1e\n" +
	"\x05Plans\x18\x03 \x03(\v2\b.pb.PlanR\x05Plans\",\n" +
	"\x12ModifyPlanResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"2\n" +
	"\x12GetPlanByIdRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\"\xa5\x01\n" +
	"\x13GetPlanByIdResponse\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1c\n" +
	"\tProjectId\x18\x02 \x01(\tR\tProjectId\x12\x16\n" +
	"\x06Branch\x18\x03 \x01(\tR\x06Branch\x12\x1a\n" +
	"\bLanguage\x18\x04 \x01(\tR\bLanguage\x12\x1e\n" +
	"\x05Plans\x18\x05 \x03(\v2\b.pb.PlanR\x05Plans2\x94\x02\n" +
	"\fagentService\x12A\n" +
	"\fgeneratePlan\x12\x17.pb.GeneratePlanRequest\x1a\x18.pb.GeneratePlanResponse\x12;\n" +
	"\n" +
	"modifyPlan\x12\x15.pb.ModifyPlanRequest\x1a\x16.pb.ModifyPlanResponse\x12>\n" +
	"\vgetPlanById\x12\x16.pb.GetPlanByIdRequest\x1a\x17.pb.GetPlanByIdResponse\x12D\n" +
	"\rimplementPlan\x12\x18.pb.ImplementPlanRequest\x1a\x19.pb.ImplementPlanResponse2D\n" +
	"\vCodeService\x125\n" +
	"\bsaveCode\x12\x13.pb.SaveCodeRequest\x1a\x14.pb.SaveCodeResponseB\x12Z\x10codev42-agent/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(*GeneratePlanRequest)(nil),   // 0: pb.GeneratePlanRequest
	(*Annotation)(nil),            // 1: pb.Annotation
	(*Plan)(nil),                  // 2: pb.Plan
	(*GeneratePlanResponse)(nil),  // 3: pb.GeneratePlanResponse
	(*SaveCodeRequest)(nil),       // 4: pb.SaveCodeRequest
	(*SaveCodeResponse)(nil),      // 5: pb.SaveCodeResponse
	(*ImplementPlanRequest)(nil),  // 6: pb.ImplementPlanRequest
	(*ImplementPlanResponse)(nil), // 7: pb.ImplementPlanResponse
	(*ModifyPlanRequest)(nil),     // 8: pb.ModifyPlanRequest
	(*ModifyPlanResponse)(nil),    // 9: pb.ModifyPlanResponse
	(*GetPlanByIdRequest)(nil),    // 10: pb.GetPlanByIdRequest
	(*GetPlanByIdResponse)(nil),   // 11: pb.GetPlanByIdResponse
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: pb.Plan.Annotations:type_name -> pb.Annotation
	2,  // 1: pb.GeneratePlanResponse.Plans:type_name -> pb.Plan
	2,  // 2: pb.ModifyPlanRequest.Plans:type_name -> pb.Plan
	2,  // 3: pb.GetPlanByIdResponse.Plans:type_name -> pb.Plan
	0,  // 4: pb.agentService.generatePlan:input_type -> pb.GeneratePlanRequest
	8,  // 5: pb.agentService.modifyPlan:input_type -> pb.ModifyPlanRequest
	10, // 6: pb.agentService.getPlanById:input_type -> pb.GetPlanByIdRequest
	6,  // 7: pb.agentService.implementPlan:input_type -> pb.ImplementPlanRequest
	4,  // 8: pb.CodeService.saveCode:input_type -> pb.SaveCodeRequest
	3,  // 9: pb.agentService.generatePlan:output_type -> pb.GeneratePlanResponse
	9,  // 10: pb.agentService.modifyPlan:output_type -> pb.ModifyPlanResponse
	11, // 11: pb.agentService.getPlanById:output_type -> pb.GetPlanByIdResponse
	7,  // 12: pb.agentService.implementPlan:output_type -> pb.ImplementPlanResponse
	5,  // 13: pb.CodeService.saveCode:output_type -> pb.SaveCodeResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
