apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.PINECONE_API_KEY | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | b64enc | quote }}