// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: diagram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 단일 다이어그램 생성 요청/응답
type GenerateDiagramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`       // 소스 코드
	Purpose       string                 `protobuf:"bytes,2,opt,name=Purpose,proto3" json:"Purpose,omitempty"` // 목적/설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDiagramRequest) Reset() {
	*x = GenerateDiagramRequest{}
	mi := &file_diagram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDiagramRequest) ProtoMessage() {}

func (x *GenerateDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDiagramRequest.ProtoReflect.Descriptor instead.
func (*GenerateDiagramRequest) Descriptor() ([]byte, []int) {
	return file_diagram_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDiagramRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GenerateDiagramRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type GenerateDiagramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagram       string                 `protobuf:"bytes,1,opt,name=Diagram,proto3" json:"Diagram,omitempty"`  // Mermaid 다이어그램 코드
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`        // 다이어그램 타입
	Success       bool                   `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"` // 성공 여부
	Error         string                 `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`      // 에러 메시지 (실패 시)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDiagramResponse) Reset() {
	*x = GenerateDiagramResponse{}
	mi := &file_diagram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDiagramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDiagramResponse) ProtoMessage() {}

func (x *GenerateDiagramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDiagramResponse.ProtoReflect.Descriptor instead.
func (*GenerateDiagramResponse) Descriptor() ([]byte, []int) {
	return file_diagram_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDiagramResponse) GetDiagram() string {
	if x != nil {
		return x.Diagram
	}
	return ""
}

func (x *GenerateDiagramResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GenerateDiagramResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateDiagramResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 모든 다이어그램 생성 요청/응답
type GenerateDiagramsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`       // 소스 코드
	Purpose       string                 `protobuf:"bytes,2,opt,name=Purpose,proto3" json:"Purpose,omitempty"` // 목적/설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDiagramsRequest) Reset() {
	*x = GenerateDiagramsRequest{}
	mi := &file_diagram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDiagramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDiagramsRequest) ProtoMessage() {}

func (x *GenerateDiagramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDiagramsRequest.ProtoReflect.Descriptor instead.
func (*GenerateDiagramsRequest) Descriptor() ([]byte, []int) {
	return file_diagram_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateDiagramsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GenerateDiagramsRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type DiagramResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagram       string                 `protobuf:"bytes,1,opt,name=Diagram,proto3" json:"Diagram,omitempty"`  // Mermaid 다이어그램 코드
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`        // 다이어그램 타입 (classDiagram, sequenceDiagram, flowchart)
	Success       bool                   `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"` // 성공 여부
	Error         string                 `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`      // 에러 메시지 (실패 시)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagramResult) Reset() {
	*x = DiagramResult{}
	mi := &file_diagram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagramResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagramResult) ProtoMessage() {}

func (x *DiagramResult) ProtoReflect() protoreflect.Message {
	mi := &file_diagram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagramResult.ProtoReflect.Descriptor instead.
func (*DiagramResult) Descriptor() ([]byte, []int) {
	return file_diagram_proto_rawDescGZIP(), []int{3}
}

func (x *DiagramResult) GetDiagram() string {
	if x != nil {
		return x.Diagram
	}
	return ""
}

func (x *DiagramResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiagramResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiagramResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateDiagramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagrams      []*DiagramResult       `protobuf:"bytes,1,rep,name=Diagrams,proto3" json:"Diagrams,omitempty"`          // 생성된 다이어그램 목록
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=SuccessCount,proto3" json:"SuccessCount,omitempty"` // 성공한 다이어그램 수
	TotalCount    int32                  `protobuf:"varint,3,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`     // 전체 다이어그램 수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDiagramsResponse) Reset() {
	*x = GenerateDiagramsResponse{}
	mi := &file_diagram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDiagramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDiagramsResponse) ProtoMessage() {}

func (x *GenerateDiagramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDiagramsResponse.ProtoReflect.Descriptor instead.
func (*GenerateDiagramsResponse) Descriptor() ([]byte, []int) {
	return file_diagram_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDiagramsResponse) GetDiagrams() []*DiagramResult {
	if x != nil {
		return x.Diagrams
	}
	return nil
}

func (x *GenerateDiagramsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *GenerateDiagramsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_diagram_proto protoreflect.FileDescriptor

const file_diagram_proto_rawDesc = "" +
	"\n" +
	"\rdiagram.proto\x12\adiagram\"F\n" +
	"\x16GenerateDiagramRequest\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x18\n" +
	"\aPurpose\x18\x02 \x01(\tR\aPurpose\"w\n" +
	"\x17GenerateDiagramResponse\x12\x18\n" +
	"\aDiagram\x18\x01 \x01(\tR\aDiagram\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x18\n" +
	"\aSuccess\x18\x03 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x04 \x01(\tR\x05Error\"G\n" +
	"\x17GenerateDiagramsRequest\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x18\n" +
	"\aPurpose\x18\x02 \x01(\tR\aPurpose\"m\n" +
	"\rDiagramResult\x12\x18\n" +
	"\aDiagram\x18\x01 \x01(\tR\aDiagram\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x18\n" +
	"\aSuccess\x18\x03 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x04 \x01(\tR\x05Error\"\x92\x01\n" +
	"\x18GenerateDiagramsResponse\x122\n" +
	"\bDiagrams\x18\x01 \x03(\v2\x16.diagram.DiagramResultR\bDiagrams\x12\"\n" +
	"\fSuccessCount\x18\x02 \x01(\x05R\fSuccessCount\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x03 \x01(\x05R\n" +
	"TotalCount2\x81\x03\n" +
	"\x0eDiagramService\x12W\n" +
	"\x10GenerateDiagrams\x12 .diagram.GenerateDiagramsRequest\x1a!.diagram.GenerateDiagramsResponse\x12Y\n" +
	"\x14GenerateClassDiagram\x12\x1f.diagram.GenerateDiagramRequest\x1a .diagram.GenerateDiagramResponse\x12\\\n" +
	"\x17GenerateSequenceDiagram\x12\x1f.diagram.GenerateDiagramRequest\x1a .diagram.GenerateDiagramResponse\x12]\n" +
	"\x18GenerateFlowchartDiagram\x12\x1f.diagram.GenerateDiagramRequest\x1a .diagram.GenerateDiagramResponseB\x1dZ\x1bcodev42/services/diagram/pbb\x06proto3"

var (
	file_diagram_proto_rawDescOnce sync.Once
	file_diagram_proto_rawDescData []byte
)

func file_diagram_proto_rawDescGZIP() []byte {
	file_diagram_proto_rawDescOnce.Do(func() {
		file_diagram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diagram_proto_rawDesc), len(file_diagram_proto_rawDesc)))
	})
	return file_diagram_proto_rawDescData
}

var file_diagram_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_diagram_proto_goTypes = []any{
	(*GenerateDiagramRequest)(nil),   // 0: diagram.GenerateDiagramRequest
	(*GenerateDiagramResponse)(nil),  // 1: diagram.GenerateDiagramResponse
	(*GenerateDiagramsRequest)(nil),  // 2: diagram.GenerateDiagramsRequest
	(*DiagramResult)(nil),            // 3: diagram.DiagramResult
	(*GenerateDiagramsResponse)(nil), // 4: diagram.GenerateDiagramsResponse
}
var file_diagram_proto_depIdxs = []int32{
	3, // 0: diagram.GenerateDiagramsResponse.Diagrams:type_name -> diagram.DiagramResult
	2, // 1: diagram.DiagramService.GenerateDiagrams:input_type -> diagram.GenerateDiagramsRequest
	0, // 2: diagram.DiagramService.GenerateClassDiagram:input_type -> diagram.GenerateDiagramRequest
	0, // 3: diagram.DiagramService.GenerateSequenceDiagram:input_type -> diagram.GenerateDiagramRequest
	0, // 4: diagram.DiagramService.GenerateFlowchartDiagram:input_type -> diagram.GenerateDiagramRequest
	4, // 5: diagram.DiagramService.GenerateDiagrams:output_type -> diagram.GenerateDiagramsResponse
	1, // 6: diagram.DiagramService.GenerateClassDiagram:output_type -> diagram.GenerateDiagramResponse
	1, // 7: diagram.DiagramService.GenerateSequenceDiagram:output_type -> diagram.GenerateDiagramResponse
	1, // 8: diagram.DiagramService.GenerateFlowchartDiagram:output_type -> diagram.GenerateDiagramResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_diagram_proto_init() }
func file_diagram_proto_init() {
	if File_diagram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diagram_proto_rawDesc), len(file_diagram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diagram_proto_goTypes,
		DependencyIndexes: file_diagram_proto_depIdxs,
		MessageInfos:      file_diagram_proto_msgTypes,
	}.Build()
	File_diagram_proto = out.File
	file_diagram_proto_goTypes = nil
	file_diagram_proto_depIdxs = nil
}
