// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: diagram.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiagramService_GenerateDiagrams_FullMethodName         = "/diagram.DiagramService/GenerateDiagrams"
	DiagramService_GenerateClassDiagram_FullMethodName     = "/diagram.DiagramService/GenerateClassDiagram"
	DiagramService_GenerateSequenceDiagram_FullMethodName  = "/diagram.DiagramService/GenerateSequenceDiagram"
	DiagramService_GenerateFlowchartDiagram_FullMethodName = "/diagram.DiagramService/GenerateFlowchartDiagram"
)

// DiagramServiceClient is the client API for DiagramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Diagram Service - Mermaid 다이어그램 생성
type DiagramServiceClient interface {
	// 모든 다이어그램 생성 (병렬 처리)
	GenerateDiagrams(ctx context.Context, in *GenerateDiagramsRequest, opts ...grpc.CallOption) (*GenerateDiagramsResponse, error)
	// 클래스 다이어그램 생성
	GenerateClassDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error)
	// 시퀀스 다이어그램 생성
	GenerateSequenceDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error)
	// 플로우차트 생성
	GenerateFlowchartDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error)
}

type diagramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagramServiceClient(cc grpc.ClientConnInterface) DiagramServiceClient {
	return &diagramServiceClient{cc}
}

func (c *diagramServiceClient) GenerateDiagrams(ctx context.Context, in *GenerateDiagramsRequest, opts ...grpc.CallOption) (*GenerateDiagramsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDiagramsResponse)
	err := c.cc.Invoke(ctx, DiagramService_GenerateDiagrams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) GenerateClassDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDiagramResponse)
	err := c.cc.Invoke(ctx, DiagramService_GenerateClassDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) GenerateSequenceDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDiagramResponse)
	err := c.cc.Invoke(ctx, DiagramService_GenerateSequenceDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) GenerateFlowchartDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDiagramResponse)
	err := c.cc.Invoke(ctx, DiagramService_GenerateFlowchartDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagramServiceServer is the server API for DiagramService service.
// All implementations must embed UnimplementedDiagramServiceServer
// for forward compatibility.
//
// Diagram Service - Mermaid 다이어그램 생성
type DiagramServiceServer interface {
	// 모든 다이어그램 생성 (병렬 처리)
	GenerateDiagrams(context.Context, *GenerateDiagramsRequest) (*GenerateDiagramsResponse, error)
	// 클래스 다이어그램 생성
	GenerateClassDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error)
	// 시퀀스 다이어그램 생성
	GenerateSequenceDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error)
	// 플로우차트 생성
	GenerateFlowchartDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error)
	mustEmbedUnimplementedDiagramServiceServer()
}

// UnimplementedDiagramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagramServiceServer struct{}

func (UnimplementedDiagramServiceServer) GenerateDiagrams(context.Context, *GenerateDiagramsRequest) (*GenerateDiagramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDiagrams not implemented")
}
func (UnimplementedDiagramServiceServer) GenerateClassDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateClassDiagram not implemented")
}
func (UnimplementedDiagramServiceServer) GenerateSequenceDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSequenceDiagram not implemented")
}
func (UnimplementedDiagramServiceServer) GenerateFlowchartDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateFlowchartDiagram not implemented")
}
func (UnimplementedDiagramServiceServer) mustEmbedUnimplementedDiagramServiceServer() {}
func (UnimplementedDiagramServiceServer) testEmbeddedByValue()                        {}

// UnsafeDiagramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagramServiceServer will
// result in compilation errors.
type UnsafeDiagramServiceServer interface {
	mustEmbedUnimplementedDiagramServiceServer()
}

func RegisterDiagramServiceServer(s grpc.ServiceRegistrar, srv DiagramServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiagramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagramService_ServiceDesc, srv)
}

func _DiagramService_GenerateDiagrams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDiagramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).GenerateDiagrams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_GenerateDiagrams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).GenerateDiagrams(ctx, req.(*GenerateDiagramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_GenerateClassDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).GenerateClassDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_GenerateClassDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).GenerateClassDiagram(ctx, req.(*GenerateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_GenerateSequenceDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).GenerateSequenceDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_GenerateSequenceDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).GenerateSequenceDiagram(ctx, req.(*GenerateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_GenerateFlowchartDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).GenerateFlowchartDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_GenerateFlowchartDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).GenerateFlowchartDiagram(ctx, req.(*GenerateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagramService_ServiceDesc is the grpc.ServiceDesc for DiagramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diagram.DiagramService",
	HandlerType: (*DiagramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDiagrams",
			Handler:    _DiagramService_GenerateDiagrams_Handler,
		},
		{
			MethodName: "GenerateClassDiagram",
			Handler:    _DiagramService_GenerateClassDiagram_Handler,
		},
		{
			MethodName: "GenerateSequenceDiagram",
			Handler:    _DiagramService_GenerateSequenceDiagram_Handler,
		},
		{
			MethodName: "GenerateFlowchartDiagram",
			Handler:    _DiagramService_GenerateFlowchartDiagram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagram.proto",
}
