// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: pb/plan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlanService_GeneratePlan_FullMethodName = "/plan.PlanService/GeneratePlan"
	PlanService_ModifyPlan_FullMethodName   = "/plan.PlanService/ModifyPlan"
	PlanService_GetPlanById_FullMethodName  = "/plan.PlanService/GetPlanById"
	PlanService_GetPlanList_FullMethodName  = "/plan.PlanService/GetPlanList"
)

// PlanServiceClient is the client API for PlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plan Service - 개발 계획 생성 및 관리
type PlanServiceClient interface {
	// 새로운 개발 계획 생성
	GeneratePlan(ctx context.Context, in *GeneratePlanRequest, opts ...grpc.CallOption) (*GeneratePlanResponse, error)
	// 기존 계획 수정
	ModifyPlan(ctx context.Context, in *ModifyPlanRequest, opts ...grpc.CallOption) (*ModifyPlanResponse, error)
	// 계획 상세 조회
	GetPlanById(ctx context.Context, in *GetPlanByIdRequest, opts ...grpc.CallOption) (*GetPlanByIdResponse, error)
	// 프로젝트의 계획 목록 조회
	GetPlanList(ctx context.Context, in *GetPlanListRequest, opts ...grpc.CallOption) (*GetPlanListResponse, error)
}

type planServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanServiceClient(cc grpc.ClientConnInterface) PlanServiceClient {
	return &planServiceClient{cc}
}

func (c *planServiceClient) GeneratePlan(ctx context.Context, in *GeneratePlanRequest, opts ...grpc.CallOption) (*GeneratePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePlanResponse)
	err := c.cc.Invoke(ctx, PlanService_GeneratePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) ModifyPlan(ctx context.Context, in *ModifyPlanRequest, opts ...grpc.CallOption) (*ModifyPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyPlanResponse)
	err := c.cc.Invoke(ctx, PlanService_ModifyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetPlanById(ctx context.Context, in *GetPlanByIdRequest, opts ...grpc.CallOption) (*GetPlanByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanByIdResponse)
	err := c.cc.Invoke(ctx, PlanService_GetPlanById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetPlanList(ctx context.Context, in *GetPlanListRequest, opts ...grpc.CallOption) (*GetPlanListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanListResponse)
	err := c.cc.Invoke(ctx, PlanService_GetPlanList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanServiceServer is the server API for PlanService service.
// All implementations must embed UnimplementedPlanServiceServer
// for forward compatibility.
//
// Plan Service - 개발 계획 생성 및 관리
type PlanServiceServer interface {
	// 새로운 개발 계획 생성
	GeneratePlan(context.Context, *GeneratePlanRequest) (*GeneratePlanResponse, error)
	// 기존 계획 수정
	ModifyPlan(context.Context, *ModifyPlanRequest) (*ModifyPlanResponse, error)
	// 계획 상세 조회
	GetPlanById(context.Context, *GetPlanByIdRequest) (*GetPlanByIdResponse, error)
	// 프로젝트의 계획 목록 조회
	GetPlanList(context.Context, *GetPlanListRequest) (*GetPlanListResponse, error)
	mustEmbedUnimplementedPlanServiceServer()
}

// UnimplementedPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanServiceServer struct{}

func (UnimplementedPlanServiceServer) GeneratePlan(context.Context, *GeneratePlanRequest) (*GeneratePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePlan not implemented")
}
func (UnimplementedPlanServiceServer) ModifyPlan(context.Context, *ModifyPlanRequest) (*ModifyPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyPlan not implemented")
}
func (UnimplementedPlanServiceServer) GetPlanById(context.Context, *GetPlanByIdRequest) (*GetPlanByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlanById not implemented")
}
func (UnimplementedPlanServiceServer) GetPlanList(context.Context, *GetPlanListRequest) (*GetPlanListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlanList not implemented")
}
func (UnimplementedPlanServiceServer) mustEmbedUnimplementedPlanServiceServer() {}
func (UnimplementedPlanServiceServer) testEmbeddedByValue()                     {}

// UnsafePlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanServiceServer will
// result in compilation errors.
type UnsafePlanServiceServer interface {
	mustEmbedUnimplementedPlanServiceServer()
}

func RegisterPlanServiceServer(s grpc.ServiceRegistrar, srv PlanServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanService_ServiceDesc, srv)
}

func _PlanService_GeneratePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GeneratePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GeneratePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GeneratePlan(ctx, req.(*GeneratePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_ModifyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).ModifyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_ModifyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).ModifyPlan(ctx, req.(*ModifyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetPlanById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlanById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlanById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlanById(ctx, req.(*GetPlanByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetPlanList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlanList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlanList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlanList(ctx, req.(*GetPlanListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanService_ServiceDesc is the grpc.ServiceDesc for PlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plan.PlanService",
	HandlerType: (*PlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlan",
			Handler:    _PlanService_GeneratePlan_Handler,
		},
		{
			MethodName: "ModifyPlan",
			Handler:    _PlanService_ModifyPlan_Handler,
		},
		{
			MethodName: "GetPlanById",
			Handler:    _PlanService_GetPlanById_Handler,
		},
		{
			MethodName: "GetPlanList",
			Handler:    _PlanService_GetPlanList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/plan.proto",
}
