// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: plan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 메시지 정의
type Annotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`               // 함수/메서드 이름
	Params        string                 `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`           // 매개변수
	Returns       string                 `protobuf:"bytes,3,opt,name=Returns,proto3" json:"Returns,omitempty"`         // 반환 타입
	Description   string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"` // 설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Annotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Annotation) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Annotation) GetReturns() string {
	if x != nil {
		return x.Returns
	}
	return ""
}

func (x *Annotation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=ClassName,proto3" json:"ClassName,omitempty"`     // 클래스명 (함수인 경우 빈 문자열)
	Annotations   []*Annotation          `protobuf:"bytes,2,rep,name=Annotations,proto3" json:"Annotations,omitempty"` // 함수/메서드 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Plan) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// GeneratePlan 요청/응답
type GeneratePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=Prompt,proto3" json:"Prompt,omitempty"`       // 사용자 프롬프트
	ProjectId     string                 `protobuf:"bytes,2,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"` // 프로젝트 ID
	Branch        string                 `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`       // 브랜치명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanRequest) Reset() {
	*x = GeneratePlanRequest{}
	mi := &file_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanRequest) ProtoMessage() {}

func (x *GeneratePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanRequest.ProtoReflect.Descriptor instead.
func (*GeneratePlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratePlanRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GeneratePlanRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GeneratePlanRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type GeneratePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 생성된 개발 계획 ID
	Language      string                 `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`    // 프로그래밍 언어
	Plans         []*Plan                `protobuf:"bytes,3,rep,name=Plans,proto3" json:"Plans,omitempty"`          // 계획 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanResponse) Reset() {
	*x = GeneratePlanResponse{}
	mi := &file_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanResponse) ProtoMessage() {}

func (x *GeneratePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanResponse.ProtoReflect.Descriptor instead.
func (*GeneratePlanResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratePlanResponse) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *GeneratePlanResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeneratePlanResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

// ModifyPlan 요청/응답
type ModifyPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 수정할 개발 계획 ID
	Language      string                 `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`    // 프로그래밍 언어
	Plans         []*Plan                `protobuf:"bytes,3,rep,name=Plans,proto3" json:"Plans,omitempty"`          // 수정된 계획 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPlanRequest) Reset() {
	*x = ModifyPlanRequest{}
	mi := &file_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPlanRequest) ProtoMessage() {}

func (x *ModifyPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPlanRequest.ProtoReflect.Descriptor instead.
func (*ModifyPlanRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyPlanRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *ModifyPlanRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ModifyPlanRequest) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type ModifyPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"` // 상태 메시지
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPlanResponse) Reset() {
	*x = ModifyPlanResponse{}
	mi := &file_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPlanResponse) ProtoMessage() {}

func (x *ModifyPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPlanResponse.ProtoReflect.Descriptor instead.
func (*ModifyPlanResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyPlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetPlanById 요청/응답
type GetPlanByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 조회할 개발 계획 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByIdRequest) Reset() {
	*x = GetPlanByIdRequest{}
	mi := &file_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByIdRequest) ProtoMessage() {}

func (x *GetPlanByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlanByIdRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlanByIdRequest) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

type GetPlanByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 개발 계획 ID
	ProjectId     string                 `protobuf:"bytes,2,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`  // 프로젝트 ID
	Branch        string                 `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`        // 브랜치명
	Language      string                 `protobuf:"bytes,4,opt,name=Language,proto3" json:"Language,omitempty"`    // 프로그래밍 언어
	Plans         []*Plan                `protobuf:"bytes,5,rep,name=Plans,proto3" json:"Plans,omitempty"`          // 계획 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByIdResponse) Reset() {
	*x = GetPlanByIdResponse{}
	mi := &file_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByIdResponse) ProtoMessage() {}

func (x *GetPlanByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPlanByIdResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlanByIdResponse) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *GetPlanByIdResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetPlanByIdResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetPlanByIdResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetPlanByIdResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

// GetPlanList 요청/응답
type GetPlanListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"` // 프로젝트 ID
	Branch        string                 `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`       // 브랜치명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanListRequest) Reset() {
	*x = GetPlanListRequest{}
	mi := &file_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanListRequest) ProtoMessage() {}

func (x *GetPlanListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanListRequest.ProtoReflect.Descriptor instead.
func (*GetPlanListRequest) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlanListRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetPlanListRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type PlanListElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanId     int64                  `protobuf:"varint,1,opt,name=DevPlanId,proto3" json:"DevPlanId,omitempty"` // 개발 계획 ID
	Prompt        string                 `protobuf:"bytes,2,opt,name=Prompt,proto3" json:"Prompt,omitempty"`        // 프롬프트
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanListElement) Reset() {
	*x = PlanListElement{}
	mi := &file_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanListElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanListElement) ProtoMessage() {}

func (x *PlanListElement) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanListElement.ProtoReflect.Descriptor instead.
func (*PlanListElement) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{9}
}

func (x *PlanListElement) GetDevPlanId() int64 {
	if x != nil {
		return x.DevPlanId
	}
	return 0
}

func (x *PlanListElement) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetPlanListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevPlanList   []*PlanListElement     `protobuf:"bytes,1,rep,name=DevPlanList,proto3" json:"DevPlanList,omitempty"` // 계획 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanListResponse) Reset() {
	*x = GetPlanListResponse{}
	mi := &file_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanListResponse) ProtoMessage() {}

func (x *GetPlanListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanListResponse.ProtoReflect.Descriptor instead.
func (*GetPlanListResponse) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlanListResponse) GetDevPlanList() []*PlanListElement {
	if x != nil {
		return x.DevPlanList
	}
	return nil
}

var File_plan_proto protoreflect.FileDescriptor

const file_plan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"plan.proto\x12\x04plan\"t\n" +
	"\n" +
	"Annotation\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Params\x18\x02 \x01(\tR\x06Params\x12\x18\n" +
	"\aReturns\x18\x03 \x01(\tR\aReturns\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\"X\n" +
	"\x04Plan\x12\x1c\n" +
	"\tClassName\x18\x01 \x01(\tR\tClassName\x122\n" +
	"\vAnnotations\x18\x02 \x03(\v2\x10.plan.AnnotationR\vAnnotations\"c\n" +
	"\x13GeneratePlanRequest\x12\x16\n" +
	"\x06Prompt\x18\x01 \x01(\tR\x06Prompt\x12\x1c\n" +
	"\tProjectId\x18\x02 \x01(\tR\tProjectId\x12\x16\n" +
	"\x06Branch\x18\x03 \x01(\tR\x06Branch\"r\n" +
	"\x14GeneratePlanResponse\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1a\n" +
	"\bLanguage\x18\x02 \x01(\tR\bLanguage\x12 \n" +
	"\x05Plans\x18\x03 \x03(\v2\n" +
	".plan.PlanR\x05Plans\"o\n" +
	"\x11ModifyPlanRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1a\n" +
	"\bLanguage\x18\x02 \x01(\tR\bLanguage\x12 \n" +
	"\x05Plans\x18\x03 \x03(\v2\n" +
	".plan.PlanR\x05Plans\",\n" +
	"\x12ModifyPlanResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"2\n" +
	"\x12GetPlanByIdRequest\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\"\xa7\x01\n" +
	"\x13GetPlanByIdResponse\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x1c\n" +
	"\tProjectId\x18\x02 \x01(\tR\tProjectId\x12\x16\n" +
	"\x06Branch\x18\x03 \x01(\tR\x06Branch\x12\x1a\n" +
	"\bLanguage\x18\x04 \x01(\tR\bLanguage\x12 \n" +
	"\x05Plans\x18\x05 \x03(\v2\n" +
	".plan.PlanR\x05Plans\"J\n" +
	"\x12GetPlanListRequest\x12\x1c\n" +
	"\tProjectId\x18\x01 \x01(\tR\tProjectId\x12\x16\n" +
	"\x06Branch\x18\x02 \x01(\tR\x06Branch\"G\n" +
	"\x0fPlanListElement\x12\x1c\n" +
	"\tDevPlanId\x18\x01 \x01(\x03R\tDevPlanId\x12\x16\n" +
	"\x06Prompt\x18\x02 \x01(\tR\x06Prompt\"N\n" +
	"\x13GetPlanListResponse\x127\n" +
	"\vDevPlanList\x18\x01 \x03(\v2\x15.plan.PlanListElementR\vDevPlanList2\x9d\x02\n" +
	"\vPlanService\x12E\n" +
	"\fGeneratePlan\x12\x19.plan.GeneratePlanRequest\x1a\x1a.plan.GeneratePlanResponse\x12?\n" +
	"\n" +
	"ModifyPlan\x12\x17.plan.ModifyPlanRequest\x1a\x18.plan.ModifyPlanResponse\x12B\n" +
	"\vGetPlanById\x12\x18.plan.GetPlanByIdRequest\x1a\x19.plan.GetPlanByIdResponse\x12B\n" +
	"\vGetPlanList\x12\x18.plan.GetPlanListRequest\x1a\x19.plan.GetPlanListResponseB\x1aZ\x18codev42/services/plan/pbb\x06proto3"

var (
	file_plan_proto_rawDescOnce sync.Once
	file_plan_proto_rawDescData []byte
)

func file_plan_proto_rawDescGZIP() []byte {
	file_plan_proto_rawDescOnce.Do(func() {
		file_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)))
	})
	return file_plan_proto_rawDescData
}

var file_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_plan_proto_goTypes = []any{
	(*Annotation)(nil),           // 0: plan.Annotation
	(*Plan)(nil),                 // 1: plan.Plan
	(*GeneratePlanRequest)(nil),  // 2: plan.GeneratePlanRequest
	(*GeneratePlanResponse)(nil), // 3: plan.GeneratePlanResponse
	(*ModifyPlanRequest)(nil),    // 4: plan.ModifyPlanRequest
	(*ModifyPlanResponse)(nil),   // 5: plan.ModifyPlanResponse
	(*GetPlanByIdRequest)(nil),   // 6: plan.GetPlanByIdRequest
	(*GetPlanByIdResponse)(nil),  // 7: plan.GetPlanByIdResponse
	(*GetPlanListRequest)(nil),   // 8: plan.GetPlanListRequest
	(*PlanListElement)(nil),      // 9: plan.PlanListElement
	(*GetPlanListResponse)(nil),  // 10: plan.GetPlanListResponse
}
var file_plan_proto_depIdxs = []int32{
	0,  // 0: plan.Plan.Annotations:type_name -> plan.Annotation
	1,  // 1: plan.GeneratePlanResponse.Plans:type_name -> plan.Plan
	1,  // 2: plan.ModifyPlanRequest.Plans:type_name -> plan.Plan
	1,  // 3: plan.GetPlanByIdResponse.Plans:type_name -> plan.Plan
	9,  // 4: plan.GetPlanListResponse.DevPlanList:type_name -> plan.PlanListElement
	2,  // 5: plan.PlanService.GeneratePlan:input_type -> plan.GeneratePlanRequest
	4,  // 6: plan.PlanService.ModifyPlan:input_type -> plan.ModifyPlanRequest
	6,  // 7: plan.PlanService.GetPlanById:input_type -> plan.GetPlanByIdRequest
	8,  // 8: plan.PlanService.GetPlanList:input_type -> plan.GetPlanListRequest
	3,  // 9: plan.PlanService.GeneratePlan:output_type -> plan.GeneratePlanResponse
	5,  // 10: plan.PlanService.ModifyPlan:output_type -> plan.ModifyPlanResponse
	7,  // 11: plan.PlanService.GetPlanById:output_type -> plan.GetPlanByIdResponse
	10, // 12: plan.PlanService.GetPlanList:output_type -> plan.GetPlanListResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_plan_proto_init() }
func file_plan_proto_init() {
	if File_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_proto_goTypes,
		DependencyIndexes: file_plan_proto_depIdxs,
		MessageInfos:      file_plan_proto_msgTypes,
	}.Build()
	File_plan_proto = out.File
	file_plan_proto_goTypes = nil
	file_plan_proto_depIdxs = nil
}
