// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.3
// source: pb/codev42.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=Prompt,proto3" json:"Prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanRequest) Reset() {
	*x = GeneratePlanRequest{}
	mi := &file_pb_codev42_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanRequest) ProtoMessage() {}

func (x *GeneratePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_codev42_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanRequest.ProtoReflect.Descriptor instead.
func (*GeneratePlanRequest) Descriptor() ([]byte, []int) {
	return file_pb_codev42_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePlanRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GeneratePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=Language,proto3" json:"Language,omitempty"`
	Plans         []string               `protobuf:"bytes,2,rep,name=Plans,proto3" json:"Plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePlanResponse) Reset() {
	*x = GeneratePlanResponse{}
	mi := &file_pb_codev42_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlanResponse) ProtoMessage() {}

func (x *GeneratePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_codev42_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlanResponse.ProtoReflect.Descriptor instead.
func (*GeneratePlanResponse) Descriptor() ([]byte, []int) {
	return file_pb_codev42_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePlanResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeneratePlanResponse) GetPlans() []string {
	if x != nil {
		return x.Plans
	}
	return nil
}

type ImplementPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=Language,proto3" json:"Language,omitempty"`
	Plans         []string               `protobuf:"bytes,2,rep,name=Plans,proto3" json:"Plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanRequest) Reset() {
	*x = ImplementPlanRequest{}
	mi := &file_pb_codev42_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanRequest) ProtoMessage() {}

func (x *ImplementPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_codev42_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanRequest.ProtoReflect.Descriptor instead.
func (*ImplementPlanRequest) Descriptor() ([]byte, []int) {
	return file_pb_codev42_proto_rawDescGZIP(), []int{2}
}

func (x *ImplementPlanRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ImplementPlanRequest) GetPlans() []string {
	if x != nil {
		return x.Plans
	}
	return nil
}

type ImplementPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   []string               `protobuf:"bytes,1,rep,name=Description,proto3" json:"Description,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementPlanResponse) Reset() {
	*x = ImplementPlanResponse{}
	mi := &file_pb_codev42_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementPlanResponse) ProtoMessage() {}

func (x *ImplementPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_codev42_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementPlanResponse.ProtoReflect.Descriptor instead.
func (*ImplementPlanResponse) Descriptor() ([]byte, []int) {
	return file_pb_codev42_proto_rawDescGZIP(), []int{3}
}

func (x *ImplementPlanResponse) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *ImplementPlanResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_pb_codev42_proto protoreflect.FileDescriptor

var file_pb_codev42_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x76, 0x34, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x48, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x22,
	0x48, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x22, 0x4d, 0x0a, 0x15, 0x49, 0x6d, 0x70,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x65, 0x68, 0x77, 0x61, 0x6e, 0x35, 0x30, 0x35, 0x2f, 0x63, 0x6f, 0x64, 0x65,
	0x76, 0x34, 0x32, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_codev42_proto_rawDescOnce sync.Once
	file_pb_codev42_proto_rawDescData = file_pb_codev42_proto_rawDesc
)

func file_pb_codev42_proto_rawDescGZIP() []byte {
	file_pb_codev42_proto_rawDescOnce.Do(func() {
		file_pb_codev42_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_codev42_proto_rawDescData)
	})
	return file_pb_codev42_proto_rawDescData
}

var file_pb_codev42_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_codev42_proto_goTypes = []any{
	(*GeneratePlanRequest)(nil),   // 0: pb.GeneratePlanRequest
	(*GeneratePlanResponse)(nil),  // 1: pb.GeneratePlanResponse
	(*ImplementPlanRequest)(nil),  // 2: pb.ImplementPlanRequest
	(*ImplementPlanResponse)(nil), // 3: pb.ImplementPlanResponse
}
var file_pb_codev42_proto_depIdxs = []int32{
	0, // 0: pb.agentService.generatePlan:input_type -> pb.GeneratePlanRequest
	2, // 1: pb.agentService.SearchEntities:input_type -> pb.ImplementPlanRequest
	1, // 2: pb.agentService.generatePlan:output_type -> pb.GeneratePlanResponse
	3, // 3: pb.agentService.SearchEntities:output_type -> pb.ImplementPlanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_codev42_proto_init() }
func file_pb_codev42_proto_init() {
	if File_pb_codev42_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_codev42_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_codev42_proto_goTypes,
		DependencyIndexes: file_pb_codev42_proto_depIdxs,
		MessageInfos:      file_pb_codev42_proto_msgTypes,
	}.Build()
	File_pb_codev42_proto = out.File
	file_pb_codev42_proto_rawDesc = nil
	file_pb_codev42_proto_goTypes = nil
	file_pb_codev42_proto_depIdxs = nil
}
