// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: analyzer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CombineCode 요청/응답
type CombineCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=Codes,proto3" json:"Codes,omitempty"`       // 조합할 코드 목록
	Purpose       string                 `protobuf:"bytes,2,opt,name=Purpose,proto3" json:"Purpose,omitempty"`   // 목적/설명
	Language      string                 `protobuf:"bytes,3,opt,name=Language,proto3" json:"Language,omitempty"` // 프로그래밍 언어
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineCodeRequest) Reset() {
	*x = CombineCodeRequest{}
	mi := &file_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineCodeRequest) ProtoMessage() {}

func (x *CombineCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineCodeRequest.ProtoReflect.Descriptor instead.
func (*CombineCodeRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *CombineCodeRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *CombineCodeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CombineCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CombineCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`        // 조합된 코드
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"` // 성공 여부
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`      // 에러 메시지 (실패 시)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombineCodeResponse) Reset() {
	*x = CombineCodeResponse{}
	mi := &file_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombineCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineCodeResponse) ProtoMessage() {}

func (x *CombineCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineCodeResponse.ProtoReflect.Descriptor instead.
func (*CombineCodeResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *CombineCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CombineCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CombineCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AnalyzeCodeSegments 요청/응답
type AnalyzeCodeSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`         // 분석할 코드
	Language      string                 `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"` // 프로그래밍 언어
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCodeSegmentsRequest) Reset() {
	*x = AnalyzeCodeSegmentsRequest{}
	mi := &file_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCodeSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCodeSegmentsRequest) ProtoMessage() {}

func (x *AnalyzeCodeSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCodeSegmentsRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeCodeSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeCodeSegmentsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AnalyzeCodeSegmentsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CodeSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLine     int32                  `protobuf:"varint,1,opt,name=StartLine,proto3" json:"StartLine,omitempty"`    // 시작 라인 (0-indexed)
	EndLine       int32                  `protobuf:"varint,2,opt,name=EndLine,proto3" json:"EndLine,omitempty"`        // 종료 라인
	Explanation   string                 `protobuf:"bytes,3,opt,name=Explanation,proto3" json:"Explanation,omitempty"` // 한국어 설명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeSegment) Reset() {
	*x = CodeSegment{}
	mi := &file_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeSegment) ProtoMessage() {}

func (x *CodeSegment) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeSegment.ProtoReflect.Descriptor instead.
func (*CodeSegment) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *CodeSegment) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *CodeSegment) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *CodeSegment) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type AnalyzeCodeSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeSegments  []*CodeSegment         `protobuf:"bytes,1,rep,name=CodeSegments,proto3" json:"CodeSegments,omitempty"` // 분석된 코드 구간 목록
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`          // 성공 여부
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`               // 에러 메시지 (실패 시)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCodeSegmentsResponse) Reset() {
	*x = AnalyzeCodeSegmentsResponse{}
	mi := &file_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCodeSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCodeSegmentsResponse) ProtoMessage() {}

func (x *AnalyzeCodeSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCodeSegmentsResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeCodeSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeCodeSegmentsResponse) GetCodeSegments() []*CodeSegment {
	if x != nil {
		return x.CodeSegments
	}
	return nil
}

func (x *AnalyzeCodeSegmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeCodeSegmentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x0eanalyzer.proto\x12\banalyzer\"`\n" +
	"\x12CombineCodeRequest\x12\x14\n" +
	"\x05Codes\x18\x01 \x03(\tR\x05Codes\x12\x18\n" +
	"\aPurpose\x18\x02 \x01(\tR\aPurpose\x12\x1a\n" +
	"\bLanguage\x18\x03 \x01(\tR\bLanguage\"Y\n" +
	"\x13CombineCodeResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"L\n" +
	"\x1aAnalyzeCodeSegmentsRequest\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x1a\n" +
	"\bLanguage\x18\x02 \x01(\tR\bLanguage\"g\n" +
	"\vCodeSegment\x12\x1c\n" +
	"\tStartLine\x18\x01 \x01(\x05R\tStartLine\x12\x18\n" +
	"\aEndLine\x18\x02 \x01(\x05R\aEndLine\x12 \n" +
	"\vExplanation\x18\x03 \x01(\tR\vExplanation\"\x88\x01\n" +
	"\x1bAnalyzeCodeSegmentsResponse\x129\n" +
	"\fCodeSegments\x18\x01 \x03(\v2\x15.analyzer.CodeSegmentR\fCodeSegments\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error2\xc1\x01\n" +
	"\x0fAnalyzerService\x12J\n" +
	"\vCombineCode\x12\x1c.analyzer.CombineCodeRequest\x1a\x1d.analyzer.CombineCodeResponse\x12b\n" +
	"\x13AnalyzeCodeSegments\x12$.analyzer.AnalyzeCodeSegmentsRequest\x1a%.analyzer.AnalyzeCodeSegmentsResponseB\x1eZ\x1ccodev42/services/analyzer/pbb\x06proto3"

var (
	file_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_proto_rawDescData []byte
)

func file_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)))
	})
	return file_analyzer_proto_rawDescData
}

var file_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analyzer_proto_goTypes = []any{
	(*CombineCodeRequest)(nil),          // 0: analyzer.CombineCodeRequest
	(*CombineCodeResponse)(nil),         // 1: analyzer.CombineCodeResponse
	(*AnalyzeCodeSegmentsRequest)(nil),  // 2: analyzer.AnalyzeCodeSegmentsRequest
	(*CodeSegment)(nil),                 // 3: analyzer.CodeSegment
	(*AnalyzeCodeSegmentsResponse)(nil), // 4: analyzer.AnalyzeCodeSegmentsResponse
}
var file_analyzer_proto_depIdxs = []int32{
	3, // 0: analyzer.AnalyzeCodeSegmentsResponse.CodeSegments:type_name -> analyzer.CodeSegment
	0, // 1: analyzer.AnalyzerService.CombineCode:input_type -> analyzer.CombineCodeRequest
	2, // 2: analyzer.AnalyzerService.AnalyzeCodeSegments:input_type -> analyzer.AnalyzeCodeSegmentsRequest
	1, // 3: analyzer.AnalyzerService.CombineCode:output_type -> analyzer.CombineCodeResponse
	4, // 4: analyzer.AnalyzerService.AnalyzeCodeSegments:output_type -> analyzer.AnalyzeCodeSegmentsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analyzer_proto_init() }
func file_analyzer_proto_init() {
	if File_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_proto_depIdxs,
		MessageInfos:      file_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_proto = out.File
	file_analyzer_proto_goTypes = nil
	file_analyzer_proto_depIdxs = nil
}
