// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: pb/analyzer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyzerService_CombineCode_FullMethodName         = "/analyzer.AnalyzerService/CombineCode"
	AnalyzerService_AnalyzeCodeSegments_FullMethodName = "/analyzer.AnalyzerService/AnalyzeCodeSegments"
)

// AnalyzerServiceClient is the client API for AnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analyzer Service - 코드 분석 및 조합
type AnalyzerServiceClient interface {
	// 여러 코드 조각을 조합하여 하나의 코드로 만듦
	CombineCode(ctx context.Context, in *CombineCodeRequest, opts ...grpc.CallOption) (*CombineCodeResponse, error)
	// 코드를 분석하여 중요 구간 설명 생성
	AnalyzeCodeSegments(ctx context.Context, in *AnalyzeCodeSegmentsRequest, opts ...grpc.CallOption) (*AnalyzeCodeSegmentsResponse, error)
}

type analyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerServiceClient(cc grpc.ClientConnInterface) AnalyzerServiceClient {
	return &analyzerServiceClient{cc}
}

func (c *analyzerServiceClient) CombineCode(ctx context.Context, in *CombineCodeRequest, opts ...grpc.CallOption) (*CombineCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombineCodeResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_CombineCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) AnalyzeCodeSegments(ctx context.Context, in *AnalyzeCodeSegmentsRequest, opts ...grpc.CallOption) (*AnalyzeCodeSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeCodeSegmentsResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_AnalyzeCodeSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerServiceServer is the server API for AnalyzerService service.
// All implementations must embed UnimplementedAnalyzerServiceServer
// for forward compatibility.
//
// Analyzer Service - 코드 분석 및 조합
type AnalyzerServiceServer interface {
	// 여러 코드 조각을 조합하여 하나의 코드로 만듦
	CombineCode(context.Context, *CombineCodeRequest) (*CombineCodeResponse, error)
	// 코드를 분석하여 중요 구간 설명 생성
	AnalyzeCodeSegments(context.Context, *AnalyzeCodeSegmentsRequest) (*AnalyzeCodeSegmentsResponse, error)
	mustEmbedUnimplementedAnalyzerServiceServer()
}

// UnimplementedAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerServiceServer struct{}

func (UnimplementedAnalyzerServiceServer) CombineCode(context.Context, *CombineCodeRequest) (*CombineCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CombineCode not implemented")
}
func (UnimplementedAnalyzerServiceServer) AnalyzeCodeSegments(context.Context, *AnalyzeCodeSegmentsRequest) (*AnalyzeCodeSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeCodeSegments not implemented")
}
func (UnimplementedAnalyzerServiceServer) mustEmbedUnimplementedAnalyzerServiceServer() {}
func (UnimplementedAnalyzerServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerServiceServer will
// result in compilation errors.
type UnsafeAnalyzerServiceServer interface {
	mustEmbedUnimplementedAnalyzerServiceServer()
}

func RegisterAnalyzerServiceServer(s grpc.ServiceRegistrar, srv AnalyzerServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzerService_ServiceDesc, srv)
}

func _AnalyzerService_CombineCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombineCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).CombineCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_CombineCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).CombineCode(ctx, req.(*CombineCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_AnalyzeCodeSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeCodeSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).AnalyzeCodeSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_AnalyzeCodeSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).AnalyzeCodeSegments(ctx, req.(*AnalyzeCodeSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzerService_ServiceDesc is the grpc.ServiceDesc for AnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.AnalyzerService",
	HandlerType: (*AnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CombineCode",
			Handler:    _AnalyzerService_CombineCode_Handler,
		},
		{
			MethodName: "AnalyzeCodeSegments",
			Handler:    _AnalyzerService_AnalyzeCodeSegments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/analyzer.proto",
}
